"""removed relationship

Revision ID: 10a848e85281
Revises: 6b196ba767f2
Create Date: 2024-09-25 18:43:43.582860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10a848e85281'
down_revision: Union[str, None] = '6b196ba767f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('business_hours_store_id_fkey', 'business_hours', type_='foreignkey')
    op.drop_constraint('store_status_store_id_fkey', 'store_status', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('store_status_store_id_fkey', 'store_status', 'stores', ['store_id'], ['id'])
    op.create_foreign_key('business_hours_store_id_fkey', 'business_hours', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###
